version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Server/Server.Dockerfile
    ports:
      - "50051:50051"


  redis:
    image: redis:alpine
    ports:
    - "6379:6379"


  client:
    build:
      context: .
      dockerfile: Client/Client.Dockerfile
    depends_on:
      - "server"
    command: ["./wait-for-it.sh", "server:50051", "--", "python3", "Client/Client.py"]

  
  weblogs:
    build:
      context: .
      dockerfile: Web_Server/Weblog.Dockerfile
    ports:
      - "8080:5000"
    depends_on:
      - "redis"
